services:
  - type: web
    name: n8n
    env: docker
    docker:
      dockerfile: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: N8N_PORT
        value: 10000