services:
  - type: web
    name: n8n
    env: docker
    docker:
      dockerfile: Dockerfile
    plan: free
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: DB_POSTGRESDB_SSL
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"